version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  python:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: python
    depends_on:
      - mongodb
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: client
    ports:
      - "8080:80"