version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  python_app:
    build: .
    container_name: python_app
    depends_on:
      - mongodb
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/code
